

const notas = [10, 6.5, 8, 7.5];

let somaDasNotas = 0;

/*notas.forEach(function (nota){
 somaDasNotas += nota;
})*/

notas.forEach(somaNotas);  // ENTENDI PORQUE CHAMA FUNÇÃO CALLBACK O METODO FOREACH SIGNIFICA QUE PARA CADA ELEMENTO DO ARRAY NOTAS ELE CHAMA A FUNÇÃO SOMANOTAS PARA SER EXECUTADA OU SEJA 
function somaNotas(nota) {  //SE TIVER DEZ ELEMENTOS NO ARRAY NOTAS DEZ VEZES A FUNCAO SOMANOTAS SERÁ CHAMADA
    somaDasNotas += nota;
}

const media = somaDasNotas / notas.length;

console.log(`a média das notas é ${media}`);


/* ENTENDI MAIS EU FIQUEI NA DUVIDA PORQUE A FUNCAO SOMANOTA É DECLARADA MAS NAO É CHAMAD A COM UM ARGUMENTO ESPECIFICO TIPO SOMANOTAS(6) POR EXEMPLO MAS NA VERDADE É CHAMADA SIM IMPLICITAMENTE NO FOREACH PORQUE NO NOTAS.FOREACH SIGNIFICA QUE ELE PARA CADA ELEMENTO OU CADA NOTA DO ARRAY NOTAS ELE EXECUTA A FUNCAO SOMANOTAS CO ARRAY POR EXEMPLO 
somaNotas(10)
somaNotas(6.5)
somaNotas(8)
somaNotas(7.5)*/